
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "AlreadyRevokedException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class AlreadyRevokedException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -1090918034692272607L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlreadyRevokedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AlreadyRevokedException_Exception(String message, AlreadyRevokedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AlreadyRevokedException_Exception(String message, AlreadyRevokedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.AlreadyRevokedException
     */
    public AlreadyRevokedException getFaultInfo() {
        return faultInfo;
    }

}
