
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ApprovalException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -9105401394672748324L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ApprovalException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ApprovalException_Exception(String message, ApprovalException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ApprovalException_Exception(String message, ApprovalException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.ApprovalException
     */
    public ApprovalException getFaultInfo() {
        return faultInfo;
    }

}
