
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ApprovalRequestExecutionException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalRequestExecutionException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 2438730374298272865L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ApprovalRequestExecutionException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ApprovalRequestExecutionException_Exception(String message, ApprovalRequestExecutionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ApprovalRequestExecutionException_Exception(String message, ApprovalRequestExecutionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.ApprovalRequestExecutionException
     */
    public ApprovalRequestExecutionException getFaultInfo() {
        return faultInfo;
    }

}
