
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "AuthorizationDeniedException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class AuthorizationDeniedException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -2669901786467284071L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AuthorizationDeniedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AuthorizationDeniedException_Exception(String message, AuthorizationDeniedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AuthorizationDeniedException_Exception(String message, AuthorizationDeniedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.AuthorizationDeniedException
     */
    public AuthorizationDeniedException getFaultInfo() {
        return faultInfo;
    }

}
