
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "EjbcaException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class EjbcaException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -764327890817485272L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EjbcaException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public EjbcaException_Exception(String message, EjbcaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public EjbcaException_Exception(String message, EjbcaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.EjbcaException
     */
    public EjbcaException getFaultInfo() {
        return faultInfo;
    }

}
