
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "MultipleMatchException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class MultipleMatchException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 8004961093684207229L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MultipleMatchException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MultipleMatchException_Exception(String message, MultipleMatchException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MultipleMatchException_Exception(String message, MultipleMatchException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.MultipleMatchException
     */
    public MultipleMatchException getFaultInfo() {
        return faultInfo;
    }

}
