
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "UserDataSourceException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class UserDataSourceException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 2196524011522327417L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserDataSourceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UserDataSourceException_Exception(String message, UserDataSourceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UserDataSourceException_Exception(String message, UserDataSourceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.UserDataSourceException
     */
    public UserDataSourceException getFaultInfo() {
        return faultInfo;
    }

}
