
package org.sharpsw.ejbcacli;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "WaitingForApprovalException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class WaitingForApprovalException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 8608065354978558890L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WaitingForApprovalException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WaitingForApprovalException_Exception(String message, WaitingForApprovalException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WaitingForApprovalException_Exception(String message, WaitingForApprovalException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.sharpsw.ejbcacli.WaitingForApprovalException
     */
    public WaitingForApprovalException getFaultInfo() {
        return faultInfo;
    }

}
